### PR TITLE
markdown italic text parser added

### PR DESCRIPTION
**Pull request by dshaw0004**
*italic* texts are enclosed by one asterisk(*)

### CODE REVIEW

**Comment by dshaw0004** [comment]
are you active with this repo ?
because I have a great idea to expand this repo

**Comment by Pasqua101** [comment]
Hey, thanks for the contribution. I am sort of active with this repo. I just have to make some fixes to some problems that came up from releasing my code as a package. Such as the testers not working and being unable to run the code on my PC. But I'm currently busy with school, so I don't think I'll be able to get to those issues until next week or the week after. In short, if you want to contribute, then please do. I'll do my best to accept it and hopefully make the fixes I need to help you test your contributions.

**Comment by dshaw0004** [comment]
I will do my best.
I already have plan ready heading and blockquote

**Comment by dshaw0004** [comment]
I also commented on your *Dev Community* post.
I am thinking about creating a framework using your package.

Features will be
- MD to html live complie
- it use flask or bottle to render pages to browser in develop
- it will have a build command which will convert all MD to html and store them in a build folder and do some extra stuffs like manifest.json

But the main problem is **what should I name it ?**

**Pull request merged**
