### PR TITLE
Added -c and --config functionality

### PR DESCRIPTION
**Pull request by Namatuzio**
Added a helpful description to give the user information on the -c or --config argument.

### CODE REVIEW

**Comment by Namatuzio** [comment]
Hey @Pasqua101 I was wondering how you wanted me to handle stylesheets with the toml config files. 

Normally, stylesheets don't have a default argument, so I was wondering if you wanted me to add one, or simply throw an error when a stylesheet isn't given in a toml file.

This is the example of the default stylesheet arg:
image
If this is implemented, I'll also update the default to keep code/functionality consistent.

annnnnnd here is the exception handled stylesheet
image


Not too sure how you would want this handled but either way is a pretty quick fix, thanks again.

**Comment by Pasqua101** [comment]
Hey, thanks for the comment and showing the two ideas. I never really thought about having a default stylesheet (but I probably could've used one). But I like the idea of providing a default stylesheet instead of throwing an error. I'm thinking of the default stylesheet sort of being like a convenience to the user to have. Since they may not have to worry about making or finding one. Thanks again for pointing this out. Please go ahead and make the change to include a default stylesheet.

**Comment by Namatuzio** [comment]
Sounds good, I'll get to committing my changes, thanks boss.

**Comment by Namatuzio** [comment]
Alright, everything is pushed and ready to be reviewed. 

Closes #18 
In this PR I have:

- Added TOML functionality with -c and --config
- Added helpful information to the -h argument
- Added a test config.toml file
- Updated the README to reflect all changes that have been made

Let me know if you want any updates or changes to be made I will gladly fix them up.

**Pull request merged**
